version: "3.8"
services:
  redis_master:
      image: redis:6
      ports:
        - "6379:6379"
        - "26379:26379"
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes: 
        - $PWD/redis_master.conf:/usr/local/etc/redis/redis.conf
  redis_replica:
      image: redis:6
      ports:
        - "6380:6379"
        - "26380:26379"
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes: 
        - $PWD/redis_replica.conf:/usr/local/etc/redis/redis.conf
